import type { ApiPropReferenceRow } from '~/api-reference/schema'

export const buttonApiReferenceEs: ApiPropReferenceRow[] = [
  {
    property: 'size',
    description: 'Define el tamano preestablecido del boton.',
    type: { value: '"x-small" | "small" | "default" | "large" | "x-large"', class: 'string' },
    default: { value: '"default" (fallback visual)', class: 'string' },
  },
  {
    property: 'color',
    description: 'Aplica el color del tema al boton (fondo/capas de estado segun variante).',
    type: { value: 'string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'hoverColor',
    description: 'Color opcional aplicado cuando el puntero pasa sobre el boton.',
    type: { value: 'string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'disabled',
    description: 'Deshabilita la interaccion y aplica estilos de estado deshabilitado.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'loading',
    description: 'Muestra el indicador de carga y bloquea interacciones de click.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'ripple',
    description: 'Activa o desactiva el efecto de interaccion ripple.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'true', class: 'boolean' },
  },
  {
    property: 'link',
    description: 'Fuerza modo de renderizado como ancla cuando es true.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'type',
    description: 'Tipo nativo del boton cuando renderiza como <button>.',
    type: { value: 'string', class: 'string' },
    default: { value: '"button" (cuando tag es button)', class: 'string' },
  },
  {
    property: 'ariaLabel',
    description: 'aria-label explicito para accesibilidad, util en botones solo icono.',
    type: { value: 'string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'outlined',
    description: 'Usa estilo outlined en lugar de fondo relleno.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'text',
    description: 'Usa estilo text con fondo transparente.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'tonal',
    description: 'Usa la variante visual tonal.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'fab',
    description: 'Activa presentacion tipo FAB; combinable con icon para layout centrado en icono.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'stacked',
    description: 'Aplica la clase de variante stacked.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'rounded',
    description: 'Aplica esquinas redondeadas tipo pill al boton.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'block',
    description: 'Expande el ancho para ocupar el espacio horizontal disponible.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'useContrastColor',
    description: 'Fuerza estrategia de color de contraste para casos tipo text/outlined.',
    type: { value: 'boolean', class: 'boolean' },
    default: { value: 'false', class: 'boolean' },
  },
  {
    property: 'elevation',
    description: 'Controla el nivel de elevacion cuando la variante admite elevacion.',
    type: { value: '"none" | "xs" | "sm" | "md" | "lg" | "xl"', class: 'string' },
    default: { value: '"sm"', class: 'string' },
  },
  {
    property: 'icon',
    description: 'Payload de icono para el contenido; soporta comportamiento icon-only si no hay slot default.',
    type: { value: 'IconPath | IconPath[] | string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'prependIcon',
    description: 'Agrega un icono antes del contenido del slot default.',
    type: { value: 'IconPath | IconPath[] | string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'appendIcon',
    description: 'Agrega un icono despues del contenido del slot default.',
    type: { value: 'IconPath | IconPath[] | string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'width',
    description: 'Define ancho explicito con numero (px) o longitud CSS en string.',
    type: { value: 'number | string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
  {
    property: 'height',
    description: 'Define alto explicito con numero (px) o longitud CSS en string.',
    type: { value: 'number | string', class: 'string' },
    default: { value: 'undefined', class: 'string' },
  },
]
